In [1]:
#hold for import statements
import pandas as pd

In [2]:
dfMaster = pd.read_csv('FinalCleanedData.csv',index_col =0)

In [3]:
dfMaster.head()

,1stFlrSF,2ndFlrSF,3SsnPorch,BedroomAbvGr,BldgType,BsmtCond,BsmtExposure,BsmtFinSF1,BsmtFinSF2,BsmtFinType1,...,SaleCondition,SalePrice,SaleType,ScreenPorch,TotRmsAbvGrd,TotalBsmtSF,WoodDeckSF,YearBuilt,YearRemodAdd,YrSold
0,856,854,0,3,0,3,3,706.0,0.0,2,...,4,208500.0,8,0,8,856.0,0,2003,2003,2008
1,1262,0,0,3,0,3,1,978.0,0.0,0,...,4,181500.0,8,0,6,1262.0,298,1976,1976,2007
2,920,866,0,3,0,3,2,486.0,0.0,2,...,4,223500.0,8,0,6,920.0,0,2001,2002,2008
3,961,756,0,3,0,1,3,216.0,0.0,0,...,0,140000.0,8,0,7,756.0,0,1915,1970,2006
4,1145,1053,0,4,0,3,0,655.0,0.0,2,...,4,250000.0,8,0,9,1145.0,192,2000,2000,2008

In [4]:
#create list of original features
OrgFeatures = list(dfMaster.columns)

#List for categorical features
objectFilter = ['BldgType', 'BsmtCond', 'BsmtExposure', 'BsmtFinType1', 'BsmtFinType2',
       'BsmtQual', 'CentralAir', 'Condition1', 'Condition2', 'DataType',
       'Electrical', 'ExterCond', 'ExterQual', 'Exterior1st', 'Exterior2nd',
       'Foundation', 'Functional', 'Heating', 'HeatingQC', 'HouseStyle',
       'KitchenQual', 'LandContour', 'LandSlope', 'LotConfig', 'LotShape',
       'MSZoning', 'MasVnrType', 'Neighborhood', 'PavedDrive', 'RoofMatl',
       'RoofStyle', 'SaleCondition', 'SaleType']

#List for int features
intFilter = ['1stFlrSF', '2ndFlrSF', '3SsnPorch', 'BedroomAbvGr', 'BsmtFinSF1',
       'BsmtFinSF2', 'BsmtFullBath', 'BsmtHalfBath', 'BsmtUnfSF',
       'EnclosedPorch', 'Fireplaces', 'FullBath', 'GarageArea', 'GarageCars',
       'GrLivArea', 'HalfBath', 'Id', 'KitchenAbvGr', 'LotArea',
       'LowQualFinSF', 'MSSubClass', 'MasVnrArea', 'MiscVal', 'MoSold',
       'OpenPorchSF', 'OverallCond', 'OverallQual', 'PoolArea', 'SalePrice',
       'ScreenPorch', 'TotRmsAbvGrd', 'TotalBsmtSF', 'WoodDeckSF', 'YearBuilt',
       'YearRemodAdd', 'YrSold']

In [5]:
#OrgFeatures

In [6]:
#Feature Engineering

#Going to try and create a few features that make sense to me.  Should condense data and help with EDA

In [7]:
#Count total number of Full and Half Baths
dfMaster['TotFullBath'] = (dfMaster['BsmtFullBath'] + dfMaster['FullBath'])
dfMaster['TotHalfBath'] = (dfMaster['BsmtHalfBath'] + dfMaster['HalfBath'])

In [8]:
#Age of House (data set is from 2011)
dfMaster['HouseAge'] = (2011 -dfMaster['YearBuilt'])

#Time since last Remodel
dfMaster['YrSinceRemod'] = (2011 - dfMaster['YearRemodAdd'])

In [9]:
#Total Square Feet
dfMaster['TotSF'] = (dfMaster['1stFlrSF'] + dfMaster['2ndFlrSF'])

In [ ]:
#Think I can use the same function over and over again.

In [10]:
def HasFunction(x):
    if x > 0:
        return(1)
    else:
        return(0)

In [11]:
dfMaster['HasBasement'] = dfMaster['BsmtFinSF1'].apply(HasFunction)
dfMaster['Has2Floor'] = dfMaster['2ndFlrSF'].apply(HasFunction)
dfMaster['HasGarage'] = dfMaster['GarageArea'].apply(HasFunction)
dfMaster['HasPool'] = dfMaster['PoolArea'].apply(HasFunction)

In [12]:
dfMaster[['HasBasement','Has2Floor','HasGarage','HasPool']]

      HasBasement  Has2Floor  HasGarage  HasPool
0               1          1          1        0
1               1          0          1        0
2               1          1          1        0
3               1          1          1        0
4               1          1          1        0
5               1          1          1        0
6               1          0          1        0
7               1          1          1        0
8               0          1          1        0
9               1          0          1        0
10              1          0          1        0
11              1          1          1        0
12              1          0          1        0
13              0          0          1        0
14              1          0          1        0
15              0          0          1        0
16              1          0          1        0
17              0          0          1        0
18              1          0          1        0
19              1          0          1        0
20              0          1          1        0
21              0          0          1        0
22              0          0          1        0
23              1          0          1        0
24              1          0          1        0
25              0          0          1        0
26              1          0          1        0
27              1          0          1        0
28              1          0          1        0
29              0          0          1        0
...           ...        ...        ...      ...
1429            0          0          1        0
1430            0          1          1        0
1431            0          0          0        0
1432            0          1          0        0
1433            0          1          0        0
1434            1          0          1        0
1435            1          0          1        0
1436            1          0          1        0
1437            0          0          1        0
1438            0          0          1        0
1439            1          0          1        0
1440            1          0          1        0
1441            1          0          1        0
1442            1          0          1        0
1443            1          0          1        0
1444            0          0          1        0
1445            1          0          1        0
1446            0          1          1        0
1447            1          0          1        0
1448            1          0          1        0
1449            1          0          0        0
1450            1          1          1        0
1451            1          0          1        0
1452            1          1          1        0
1453            0          1          0        0
1454            0          1          0        0
1455            1          1          1        0
1456            1          0          1        0
1457            1          0          0        0
1458            1          1          1        0

[2919 rows x 4 columns]

In [13]:
dfMaster.to_csv('dfFeatureEngineering.csv')